options:
  realm:
    type: string
    default: EXAMPLE.COM
    description: |
      Kerberos Realm. Currently only supports a single entry.
  domain:
    type: string
    default: EXAMPLE.COM
    description: |
      Kerberos domain. Currently only supports a single entry.
  kdc-address:
    type: string
    default:
    description: |
      IP Address or hostname of the remote KDC or Kerberos enabled AD
      server.
  admin-server-address:
    type: string
    default:
    description: |
      IP Address or hostname of the remote admin server.
  user:
    type: string
    default: ubuntu
    description: |
      Local user to perform domain join under, defaults to ubuntu.
  ticket-renewal-interval:
    type: int
    default: 60
    description: |
      Duration in minutes for ticket renewal.
