options:
  realm:
    type: string
    default: EXAMPLE.COM
    description: |
      Kerberos Realm. Currently only supports a single entry.
  domain:
    type: string
    default: EXAMPLE.COM
    description: |
      Kerberos domain. Currently only supports a single entry.
  kdc-address:
    type: string
    default:
    description: |
      IP Address or hostname of the remote KDC or Kerberos enabled AD
      server.
  admin-server-address:
    type: string
    default:
    description: |
      IP Address or hostname of the remote admin server.
  user:
    type: string
    default: ubuntu
    description: |
      Local user to perform domain join under, defaults to ubuntu.
  principal:
    type: string
    default: host/{hostname}
    description: |
      principal to use when adding the server, e.g. "host/HOSTNAME.example.com"
      This variable is templated.  You can use the following variable substitutions
      {hostname} - the output of 'hostname -f' with no additional casing
      {fqdn} - lower-cased FQDN of the node
      {FQDN} - upper-cased FQDN of the node
      {short} - lower-cased short name of the node
      {SHORT} - upper-cased short name of the node
  ticket-renewal-interval:
    type: int
    default: 60
    description: |
      Duration in minutes for ticket renewal.
  skip-kinit:
    type: boolean
    default: false
    description: |
      Set true to skip 'kinit' and 'krenew' commands and only write
      /etc/krb5.conf and the supplied keytab to /etc/krb5.keytab
